import argparse
import csv
from pathlib import Path
from typing import Iterable, Optional

import numpy as np


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Convert HZY HSPN CZI slides listed in hzy_hspn_manifest.csv to TIFF files "
            "with slide IDs matching exported annotation JSON files."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--manifest-csv", required=True, help="CSV generated by export_hzy_slice_db_annotations.py")
    parser.add_argument("--output-dir", required=True, help="Directory where converted TIFF files will be written")
    parser.add_argument(
        "--reader",
        choices=("auto", "aicspylibczi", "czifile", "tifffile"),
        default="auto",
        help="CZI reader backend",
    )
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing TIFF files")
    parser.add_argument("--limit", type=int, default=0, help="Optional slide limit for quick conversion tests")
    return parser.parse_args()


def read_manifest(manifest_csv: Path):
    with manifest_csv.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            slide_id = (row.get("slide_id") or "").strip()
            czi_path = (row.get("czi_path") or "").strip()
            if slide_id and czi_path:
                yield slide_id, Path(czi_path)


def squeeze_and_select_image(array: np.ndarray) -> np.ndarray:
    array = np.asarray(array)

    while array.ndim > 2 and 1 in array.shape:
        array = np.squeeze(array)

    if array.ndim == 2:
        return array

    if array.ndim == 3:
        if array.shape[-1] in (1, 3, 4):
            return array[..., :3] if array.shape[-1] == 4 else array
        if array.shape[0] in (1, 3, 4):
            moved = np.moveaxis(array, 0, -1)
            return moved[..., :3] if moved.shape[-1] == 4 else moved

    # For arrays with scene/time/z axes, keep the first plane of non-spatial axes.
    if array.ndim > 3:
        spatial_axes = sorted(range(array.ndim), key=lambda axis: array.shape[axis])[-2:]
        channel_axis: Optional[int] = None
        for axis, size in enumerate(array.shape):
            if axis not in spatial_axes and size in (1, 3, 4):
                channel_axis = axis
                break

        index = []
        for axis in range(array.ndim):
            if axis in spatial_axes or axis == channel_axis:
                index.append(slice(None))
            else:
                index.append(0)
        selected = array[tuple(index)]
        if channel_axis is not None:
            kept_axes = [axis for axis in range(array.ndim) if axis in spatial_axes or axis == channel_axis]
            new_channel_axis = kept_axes.index(channel_axis)
            selected = np.moveaxis(selected, new_channel_axis, -1)
        return squeeze_and_select_image(selected)

    raise ValueError("Could not normalize CZI image array with shape {}".format(array.shape))


def normalize_dtype(array: np.ndarray) -> np.ndarray:
    array = np.asarray(array)
    if array.dtype == np.uint8:
        return array

    if np.issubdtype(array.dtype, np.integer):
        info = np.iinfo(array.dtype)
        if info.max <= 255:
            return array.astype(np.uint8)
        return np.clip(array.astype(np.float32) / float(info.max) * 255.0, 0, 255).astype(np.uint8)

    max_value = float(np.nanmax(array)) if array.size else 1.0
    min_value = float(np.nanmin(array)) if array.size else 0.0
    if max_value <= 1.0 and min_value >= 0.0:
        return np.clip(array * 255.0, 0, 255).astype(np.uint8)
    return np.clip(array, 0, 255).astype(np.uint8)


def ensure_rgb(array: np.ndarray) -> np.ndarray:
    array = squeeze_and_select_image(array)
    array = normalize_dtype(array)

    if array.ndim == 2:
        return np.stack([array, array, array], axis=-1)

    if array.ndim == 3:
        if array.shape[-1] == 1:
            return np.repeat(array, 3, axis=-1)
        if array.shape[-1] >= 3:
            return array[..., :3]

    raise ValueError("Expected 2D grayscale or RGB image, got shape {}".format(array.shape))


def read_with_aicspylibczi(czi_path: Path) -> np.ndarray:
    from aicspylibczi import CziFile

    czi = CziFile(str(czi_path))
    try:
        image = czi.read_mosaic(C=0, scale_factor=1.0)
    except Exception:
        image = czi.read_image()[0]
    return np.asarray(image)


def read_with_czifile(czi_path: Path) -> np.ndarray:
    import czifile

    return np.asarray(czifile.imread(str(czi_path)))


def read_with_tifffile(czi_path: Path) -> np.ndarray:
    import tifffile

    return np.asarray(tifffile.imread(str(czi_path)))


def read_czi(czi_path: Path, reader: str) -> np.ndarray:
    attempts: Iterable[str]
    if reader == "auto":
        attempts = ("aicspylibczi", "czifile", "tifffile")
    else:
        attempts = (reader,)

    errors = []
    for backend in attempts:
        try:
            if backend == "aicspylibczi":
                return read_with_aicspylibczi(czi_path)
            if backend == "czifile":
                return read_with_czifile(czi_path)
            if backend == "tifffile":
                return read_with_tifffile(czi_path)
        except Exception as exc:  # noqa: BLE001 - collect backend failures for a useful final error.
            errors.append("{}: {}".format(backend, exc))

    raise RuntimeError(
        "Failed to read {}. Tried backends: {}. Install a CZI reader such as "
        "`pip install aicspylibczi` or export TIFFs with the scanner software.".format(
            czi_path,
            " | ".join(errors),
        )
    )


def write_tiff(image: np.ndarray, output_path: Path) -> None:
    import tifffile

    output_path.parent.mkdir(parents=True, exist_ok=True)
    tifffile.imwrite(
        str(output_path),
        image,
        bigtiff=True,
        photometric="rgb",
        metadata=None,
    )


def main():
    args = parse_args()
    manifest_csv = Path(args.manifest_csv)
    output_dir = Path(args.output_dir)

    if not manifest_csv.exists():
        raise FileNotFoundError("Manifest CSV does not exist: {}".format(manifest_csv))

    converted = 0
    skipped = 0
    for index, (slide_id, czi_path) in enumerate(read_manifest(manifest_csv), start=1):
        if args.limit > 0 and converted >= args.limit:
            break

        output_path = output_dir / "{}.tiff".format(slide_id)
        if output_path.exists() and not args.overwrite:
            print("[skip] {} already exists".format(output_path))
            skipped += 1
            continue

        print("[{}] Reading {}".format(index, czi_path))
        image = ensure_rgb(read_czi(czi_path, args.reader))
        print("    Writing {} with shape {}".format(output_path, image.shape))
        write_tiff(image, output_path)
        converted += 1

    print("Converted:", converted)
    print("Skipped:", skipped)
    print("Output directory:", output_dir)


if __name__ == "__main__":
    main()
